import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import TopNav from "./_components/Top-Nav";
import { Toaster } from "~/components/ui/toaster";
import Sidebar from "./dashboard/_components/Side-Bar";
import AllProviders from "~/components/AllProviders";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>

      <body className="flex flex-col ">
        <AllProviders>
          <TopNav />
          <Toaster />
          <div className="flex">
            <Sidebar />
            <div className="flex-1 overflow-auto h-screen w-full">
              {children}
            </div>
          </div>
        </AllProviders>
      </body>


    </html>
  );
}
